# permissions for end users to view configmatches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmatch-viewer-role
rules:
- apiGroups:
  - phoban.io.my.domain
  resources:
  - configmatches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - phoban.io.my.domain
  resources:
  - configmatches/status
  verbs:
  - get
