apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- deployment.yaml
- configmatch.yaml
configMapGenerator:
- name: network-conf
  options:
    labels:
      config.matcher.io/group: networking
  envs:
  - network-conf.env
